### ISSUE TITLE
Latest update broke script_maker

### ISSUE THREAD

**Issue by bnlawrence** [aidansedgewick/june_runs#24]
Rather than push a pull request for a tiny change.

Note that 
```
                save_dir = self._get_script_dir(i)
                if directory is None:
                    print(f'None, {save_dir}')
                    output_dir = save_dir / f"run_{i:03d}"
                    stdout_name = f"run_{i:03d}"
                else:
                    print(f'Exists, {save_dir}, {directory}')
                    output_dir = save_dir / f"{directory}/run_{i:03d}"
                    directory_name = str(directory).split("/")[-1]
                    stdout_name = f"{directory_name}/run_{i:03d}"
```
fails for me because save_dir has already got run_000 in it ...
```
None, /home/users/lawrence/work/results_16/runs/run_000
Traceback (most recent call last):
  File "setup_run.py", line 205, in <module>
    run_setup.script_maker.write_scripts(directories_to_run)
  File "/home/users/lawrence/J4/june_runs/june_runs/script_maker.py", line 191, in write_scripts
    assert output_dir.is_dir(), f"FAILURE: {output_dir} is not a directory" 
AssertionError: FAILURE: /home/users/lawrence/work/results_16/runs/run_000/run_000 is not a directory
```
I can hack ahead in my branch, but in case there was an underlying reason for this change ...

**Comment by arnauqb** [comment]
Should be solved now

**Comment by arnauqb** [comment]
This is  a bug I introduced when adding support for running multiple baseline policy filenames, basically the default_baseline_policy path now supports the use of '*' to get a list of policy parameter files, and each set of runs is saved accordingly to a different folder. I forgot to check that it was still working in the regular case.

**Comment by bnlawrence** [comment]
Not yet ...  unless the fix is in the config file. I'm still getting a problem because `save_dir` is already arriving as `/home/users/lawrence/work/results_14/runs/run_000`.

**Comment by bnlawrence** [comment]
Ah, yes it is, sorry, failed to properly apply the update to my working copy.
